language: python
python:
    - "2.7"
    - "3.4"
install:
    - "pip install --use-wheel --use-mirrors -r requirements.txt"
    - "pip install --use-wheel --use-mirrors coverage coveralls"
script:
    - "coverage run --source=app setup.py test"
after_success:
    coveralls
