language: python
sudo: false
python:
    - "2.7"
    - "3.4"
install:
    - "pip install --use-wheel -r requirements.txt"
    - "pip install --use-wheel coverage coveralls"
script:
    - "coverage run --source=gir setup.py test"
after_success:
    coveralls
