DEBUG = True
FLASK_PORT = 5180
STATIC_URL = 'http://188.226.245.90/static/'
SLACK_TOKEN = 'xoxb-3724390083-OaNvuxp0CbYdo0fiy5kPBcWE'
SLACK_ROOM = '#bos-ama'
SLACK_USER = 'gir'
SLACK_HOST = 'gir'
RQ_DEFAULT_HOST = 'localhost'
RQ_DEFAULT_PORT = 6479
RQ_DEFAULT_PASSWORD = None
RQ_DEFAULT_DB = 0
COUCHDB_SERVER = 'localhost:5984'
COUCHDB_DATABASE = 'gir-config'

FLASK_DEBUG_DISABLE_STRICT = True
